### PR TITLE
Publication page

### PR DESCRIPTION
**Pull request by feffemannen**
This is a first try for a list of publications. To do: Sorting and cleaning up.

### CODE REVIEW

**Comment by greleigh** [comment]
Looks (very) promising! Addresses Issue #49

**Comment by feffemannen** [comment]
It seems to work on my side at least. 

I see that commit 5a3ce230ede11ed50d9c4525c297df14daa15d6d was wrongly included in the pull request. Not sure how to delete it, but it doesn't matter.

**Comment by feffemannen** [comment]
Sorting should be sorted out now. And removed the script from being published! Please double check that.

**Comment by greleigh** [comment]
Updated PR to main branch. Will (/should) return to this asap

**Pull request merged**
